### ISSUE TITLE
时间选择的封装提供了UI的datePickerModel，但是数据不是DateTime就会炸了

### ISSUE THREAD

**Issue by hanq** [caoyunxiao/YXPickerView#2]
RT：时间选择的封装提供了UI的datePickerModel，但是数据不是DateTime就会炸了。
比如说我datePickerModel = UIDatePickerModeDate的时候，UI是yyyy-MM-dd，但是实际数据要是要yyyy-MM-dd HH:mm:ss才可以正常运行，否则就原地爆炸了。

**Comment by charlesYun** [comment]
这个问题确实存在，我抽空改下吧
